# Uncomment these two line to add support for encoders to your firmware
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

CONFIG_ZMK_POINTING=y

# Uncomment the following line to enable the OLED Display
CONFIG_ZMK_DISPLAY=y

# Uncomment the following lines to enable RGB underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y

CONFIG_ZMK_STUDIO_LOCKING=n

# Increase intensity of BT signal to +8 (from -20 to +8)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Additional parameters for Bluetooth RZ616
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

# Windows experimental specific corrections
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# Enable mouse functions like scrolling
CONFIG_ZMK_MOUSE=y

# Enable dedicated work queue for display to improve performance
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=15000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
